Repository PalisadoesFoundation/talawa-admin, pull requests merged in 2023-12, with the labels that each got.

#1150 fix: improve code coverage for src/components/Advertisements/core/Adv…
  src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.test.tsx
  src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.tsx
Labels: area/tests

#1168 Fixed admin card navigation in dashboard
  src/screens/OrganizationDashboard/OrganizationDashboard.tsx
  src/screens/OrganizationPeople/OrganizationPeople.tsx
Labels: bug

#1164 fix: Fixed overflow of event registrants
  src/components/EventRegistrantsModal/EventRegistrantsModal.tsx
Labels: bug, component/api

#1165 fix: improve code coverage for src/screens/OrgPost/OrgPost.test.tsx
  src/components/OrgPostCard/OrgPostCard.test.tsx
  src/components/OrgPostCard/OrgPostCard.tsx
  src/screens/OrgPost/OrgPost.test.tsx
Labels: area/tests

#1169 Enabling editing an advertisement
  public/locales/en.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/sp.json
  public/locales/zh.json
  src/GraphQl/Mutations/mutations.ts
  src/components/Advertisements/Advertisements.tsx
  src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.module.css
  src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.test.tsx
  src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.tsx
  src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.module.css
  src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.tsx
Labels: no-pr-activity
