Repository PalisadoesFoundation/talawa-admin, pull requests merged in 2024-03, with the labels that each got.

#1645 Refactored setup.ts and Added Tests
  setup.ts
  src/setup/askForCustomPort/askForCustomPort.test.ts
  src/setup/askForCustomPort/askForCustomPort.ts
  src/setup/askForTalawaApiUrl/askForTalawaApiUrl.test.ts
  src/setup/askForTalawaApiUrl/askForTalawaApiUrl.ts
  src/setup/checkConnection/checkConnection.test.ts
  src/setup/checkConnection/checkConnection.ts
  src/setup/checkEnvFile/checkEnvFile.test.ts
  src/setup/checkEnvFile/checkEnvFile.ts
  src/setup/validateRecaptcha/validateRecaptcha.test.ts
  src/setup/validateRecaptcha/validateRecaptcha.ts
  tsconfig.json
Labels: Ready 4 PR Review

#1629 USER REDESIGN: redesign the Create Event Modal for the talawa user portal
  public/locales/en.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/sp.json
  public/locales/zh.json
  src/screens/UserPortal/Events/Events.module.css
  src/screens/UserPortal/Events/Events.test.tsx
  src/screens/UserPortal/Events/Events.tsx
Labels: Ready 4 PR Review

#1628 redesign: user portal organization screen
  public/locales/en.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/sp.json
  public/locales/zh.json
  src/GraphQl/Mutations/OrganizationMutations.ts
  src/GraphQl/Mutations/mutations.ts
  src/GraphQl/Queries/OrganizationQueries.ts
  src/components/UserPortal/OrganizationCard/OrganizationCard.module.css
  src/components/UserPortal/OrganizationCard/OrganizationCard.test.tsx
  src/components/UserPortal/OrganizationCard/OrganizationCard.tsx
  src/components/UserPortal/OrganizationNavbar/OrganizationNavbar.test.tsx
  src/components/UserPortal/UserSidebar/UserSidebar.module.css
  src/components/UserPortal/UserSidebar/UserSidebar.tsx
  src/screens/UserPortal/Donate/Donate.test.tsx
  src/screens/UserPortal/Organizations/Organizations.module.css
  src/screens/UserPortal/Organizations/Organizations.test.tsx
  src/screens/UserPortal/Organizations/Organizations.tsx
Labels: Ready 4 PR Review

#1592 Fixes Organization Not Found in Left Drawer
  src/components/LeftDrawer/LeftDrawer.module.css
  src/components/LeftDrawer/LeftDrawer.test.tsx
  src/components/LeftDrawer/LeftDrawer.tsx
  src/components/LeftDrawerOrg/LeftDrawerOrg.module.css
  src/components/LeftDrawerOrg/LeftDrawerOrg.test.tsx
  src/components/LeftDrawerOrg/LeftDrawerOrg.tsx
  src/components/OrganizationScreen/OrganizationScreen.test.tsx
  src/components/OrganizationScreen/OrganizationScreen.tsx
  src/components/SuperAdminScreen/SuperAdminScreen.test.tsx
  src/components/SuperAdminScreen/SuperAdminScreen.tsx
  src/screens/MemberDetail/MemberDetail.test.tsx
  src/screens/MemberDetail/MemberDetail.tsx
Labels: Ready 4 PR Review

#1616 refactor: Created Unified Login/Register Component for User and Admin Portals
  public/locales/en.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/sp.json
  public/locales/zh.json
  src/App.tsx
  src/components/LoginPortalToggle/LoginPortalToggle.test.tsx
  src/components/LoginPortalToggle/LoginPortalToggle.tsx
  src/components/UserPortal/OrganizationNavbar/OrganizationNavbar.tsx
  src/components/UserPortal/SecuredRouteForUser/SecuredRouteForUser.tsx
  src/components/UserPortal/UserNavbar/UserNavbar.tsx
  src/screens/LoginPage/LoginPage.test.tsx
  src/screens/LoginPage/LoginPage.tsx
  src/screens/UserPortal/UserLoginPage/UserLoginPage.module.css
  src/screens/UserPortal/UserLoginPage/UserLoginPage.test.tsx
  src/screens/UserPortal/UserLoginPage/UserLoginPage.tsx
Labels: Ready 4 PR Review

#1568 Organization People Revamp design
  README.md
  public/images/svg/profiledefault.svg
  public/locales/en.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/sp.json
  public/locales/zh.json
  src/components/OrgAdminListCard/OrgAdminListCard.test.tsx
  src/components/OrgAdminListCard/OrgAdminListCard.tsx
  src/components/OrgPeopleListCard/OrgPeopleListCard.test.tsx
  src/components/OrgPeopleListCard/OrgPeopleListCard.tsx
  src/components/UserListCard/UserListCard.test.tsx
  src/components/UserListCard/UserListCard.tsx
  src/screens/OrganizationPeople/OrganizationPeople.module.css
  src/screens/OrganizationPeople/OrganizationPeople.test.tsx
  src/screens/OrganizationPeople/OrganizationPeople.tsx
Labels: Ready 4 PR Review

#1613 Fixes ReCaptcha Fail during login
  src/constants.ts
  src/screens/LoginPage/LoginPage.test.tsx
  src/screens/LoginPage/LoginPage.tsx
Labels: Ready 4 PR Review

#1660 Bug Report: Join Organization Error on "View All Organizations" Page Fixed ✅
  public/locales/en.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/sp.json
  public/locales/zh.json
  src/components/UserPortal/OrganizationCard/OrganizationCard.test.tsx
  src/components/UserPortal/OrganizationCard/OrganizationCard.tsx
Labels: Ready 4 PR Review

#1664 Feat/funds
  public/locales/en.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/sp.json
  public/locales/zh.json
  src/App.tsx
  src/GraphQl/Mutations/FundMutation.ts
  src/GraphQl/Queries/OrganizationQueries.ts
  src/assets/svgs/funds.svg
  src/components/IconComponent/IconComponent.test.tsx
  src/components/IconComponent/IconComponent.tsx
  src/screens/OrganizationFunds/FundArchiveModal.tsx
  src/screens/OrganizationFunds/FundCreateModal.tsx
  src/screens/OrganizationFunds/FundDeleteModal.tsx
  src/screens/OrganizationFunds/FundUpdateModal.tsx
  src/screens/OrganizationFunds/OrganizationFunds.module.css
  src/screens/OrganizationFunds/OrganizationFunds.test.tsx
  src/screens/OrganizationFunds/OrganizationFunds.tsx
  src/screens/OrganizationFunds/OrganizationFundsMocks.tsx
  src/state/reducers/routesReducer.test.ts
  src/state/reducers/routesReducer.ts
  src/utils/interfaces.ts
Labels: Ready 4 PR Review

#1669 feat: Add Action Items to Event Dashboard
  public/locales/en.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/sp.json
  public/locales/zh.json
  src/components/ActionItems/ActionItemsContainer.module.css
  src/components/ActionItems/ActionItemsContainer.test.tsx
  src/components/ActionItems/ActionItemsContainer.tsx
  src/components/ActionItems/ActionItemsContainerMocks.ts
  src/components/ActionItems/ActionItemsContainerProps.ts
  src/components/ActionItems/ActionItemsModal.test.tsx
  src/components/ActionItems/ActionItemsModal.tsx
  src/components/ActionItems/ActionItemsModalBody.tsx
  src/components/ActionItems/ActionItemsWrapper.module.css
  src/components/ActionItems/ActionItemsWrapper.test.tsx
  src/components/ActionItems/ActionItemsWrapper.tsx
  src/components/ActionItemsContainer/ActionItemsContainer.module.css
  src/components/ActionItemsContainer/ActionItemsContainer.tsx
  src/components/LeftDrawerEvent/LeftDrawerEvent.tsx
  src/components/OrganizationScreen/OrganizationScreen.tsx
  src/screens/EventDashboard/EventDashboard.test.tsx
  src/screens/OrganizationActionItems/ActionItemUpdateModal.tsx
  src/screens/OrganizationActionItems/OrganizationActionItemMocks.ts
  src/screens/OrganizationActionItems/OrganizationActionItems.module.css
  src/screens/OrganizationActionItems/OrganizationActionItems.test.tsx
  src/screens/OrganizationActionItems/OrganizationActionItems.tsx
  src/screens/OrganizationActionItems/OrganizationActionItemsErrorMocks.ts
Labels: Ready 4 PR Review

#1665 upgrade: add sass instead of node-sass
  CODE_STYLE.md
  package-lock.json
  package.json
  src/assets/css/app.css
  src/assets/css/app.css.map
Labels: Ready 4 PR Review

#1697 Fixed: App can only be accessed on localhost
  INSTALLATION.md
  package-lock.json
  src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.test.tsx
Labels: Ready 4 PR Review

#1719 Added support to add members in an organization
  .github/workflows/pull-request.yml
  public/locales/en.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/sp.json
  public/locales/zh.json
  src/GraphQl/Mutations/mutations.ts
  src/GraphQl/Queries/Queries.ts
  src/screens/OrganizationPeople/AddMember.tsx
  src/screens/OrganizationPeople/OrganizationPeople.module.css
  src/screens/OrganizationPeople/OrganizationPeople.test.tsx
  src/screens/OrganizationPeople/OrganizationPeople.tsx
Labels: Ready 4 PR Review

#1690 Fixed Unable to Open User Home & Added Complete test coverage for Home
  src/assets/svgs/article.svg
  src/assets/svgs/media.svg
  src/assets/svgs/userEvent.svg
  src/components/UserPortal/PostCard/PostCard.tsx
  src/components/UserPortal/StartPostModal/StartPostModal.module.css
  src/components/UserPortal/StartPostModal/StartPostModal.test.tsx
  src/components/UserPortal/StartPostModal/StartPostModal.tsx
  src/screens/UserPortal/Home/Home.module.css
  src/screens/UserPortal/Home/Home.test.tsx
  src/screens/UserPortal/Home/Home.tsx
  src/utils/interfaces.ts
Labels: Ready 4 PR Review

#1729 Fixes usage of userType in OrganizationPeople screen
  src/screens/OrganizationPeople/OrganizationPeople.test.tsx
  src/screens/OrganizationPeople/OrganizationPeople.tsx
Labels: Ready 4 PR Review

#1715 Added action check for different source and target branches
  .github/workflows/pull-request.yml
Labels: Ready 4 PR Review

#1755 Minor tweaks in admin
  public/locales/en.json
  src/components/Advertisements/Advertisements.tsx
  src/screens/OrgSettings/OrgSettings.tsx
  src/screens/OrganizationEvents/OrganizationEvents.test.tsx
  src/screens/OrganizationEvents/OrganizationEvents.tsx
Labels: Ready 4 PR Review

#1700 Strict lint and update PR workflow
  .eslintrc.json
  .github/workflows/pull-request.yml
  package-lock.json
  package.json
Labels: Ready 4 PR Review

#1694 User - People UI - Redesign
  public/locales/en.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/sp.json
  public/locales/zh.json
  src/GraphQl/Queries/Queries.ts
  src/components/UserPortal/OrganizationSidebar/OrganizationSidebar.test.tsx
  src/components/UserPortal/PeopleCard/PeopleCard.module.css
  src/components/UserPortal/PeopleCard/PeopleCard.test.tsx
  src/components/UserPortal/PeopleCard/PeopleCard.tsx
  src/screens/OrganizationPeople/OrganizationPeople.test.tsx
  src/screens/UserPortal/Chat/Chat.test.tsx
  src/screens/UserPortal/People/People.module.css
  src/screens/UserPortal/People/People.test.tsx
  src/screens/UserPortal/People/People.tsx
Labels: Ready 4 PR Review

#1787 Fixed Redirect Issues on Reopening baseURL
  src/screens/LoginPage/LoginPage.test.tsx
  src/screens/LoginPage/LoginPage.tsx
Labels: userTypeFix

#1696 Revamp and Modular Event Screen
  package.json
  public/locales/en.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/sp.json
  public/locales/zh.json
  src/components/ActionItems/ActionItemsModal.test.tsx
  src/components/EventCalendar/EventCalendar.module.css
  src/components/EventCalendar/EventCalendar.test.tsx
  src/components/EventCalendar/EventCalendar.tsx
  src/components/EventCalendar/EventHeader.test.tsx
  src/components/EventCalendar/EventHeader.tsx
  src/components/UserPortal/OrganizationCard/OrganizationCard.test.tsx
  src/screens/OrganizationDashboard/OrganizationDashboard.tsx
  src/screens/OrganizationEvents/OrganizationEvents.module.css
  src/screens/OrganizationEvents/OrganizationEvents.test.tsx
  src/screens/OrganizationEvents/OrganizationEvents.tsx
Labels: figma, Ready 4 PR Review

#1721 SideTweaks/Changes in leftdrawer and title section
  package-lock.json
  public/images/svg/angleDown.svg
  src/components/LeftDrawer/LeftDrawer.test.tsx
  src/components/LeftDrawer/LeftDrawer.tsx
  src/components/LeftDrawerOrg/LeftDrawerOrg.test.tsx
  src/components/LeftDrawerOrg/LeftDrawerOrg.tsx
  src/components/OrganizationScreen/OrganizationScreen.module.css
  src/components/OrganizationScreen/OrganizationScreen.test.tsx
  src/components/OrganizationScreen/OrganizationScreen.tsx
  src/components/ProfileDropdown/profileDropdown.module.css
  src/components/ProfileDropdown/profileDropdown.test.tsx
  src/components/ProfileDropdown/profileDropdown.tsx
  src/components/SuperAdminScreen/SuperAdminScreen.tsx
  src/screens/Users/UsersMocks.ts
Labels: figma, Ready 4 PR Review

#1649 Feature: Ability to change pre-login imagery
  public/locales/en.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/sp.json
  public/locales/zh.json
  src/App.tsx
  src/GraphQl/Mutations/mutations.ts
  src/GraphQl/Queries/Queries.ts
  src/assets/css/app.css
  src/assets/scss/components/_pagination.scss
  src/assets/svgs/social-icons/index.tsx
  src/components/LeftDrawer/LeftDrawer.test.tsx
  src/components/LeftDrawer/LeftDrawer.tsx
  src/components/SuperAdminScreen/SuperAdminScreen.tsx
  src/constants.ts
  src/screens/CommunityProfile/CommunityProfile.module.css
  src/screens/CommunityProfile/CommunityProfile.test.tsx
  src/screens/CommunityProfile/CommunityProfile.tsx
  src/screens/LoginPage/LoginPage.module.css
  src/screens/LoginPage/LoginPage.test.tsx
  src/screens/LoginPage/LoginPage.tsx
Labels: figma

#1806 Redesigned the Event Management's Dashboard tab for the talawa admin portal
  src/components/LeftDrawerEvent/LeftDrawerEventWrapper.module.css
  src/components/LeftDrawerEvent/LeftDrawerEventWrapper.tsx
  src/screens/EventDashboard/EventDashboard.mocks.ts
  src/screens/EventDashboard/EventDashboard.module.css
  src/screens/EventDashboard/EventDashboard.tsx
Labels: Ready 4 PR Review

#1667 Updated UI for Admin-> User Profile
  package-lock.json
  package.json
  public/locales/en.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/sp.json
  public/locales/zh.json
  src/GraphQl/Mutations/mutations.ts
  src/GraphQl/Queries/Queries.ts
  src/components/Avatar/Avatar.tsx
  src/components/DynamicDropDown/DynamicDropDown.module.css
  src/components/DynamicDropDown/DynamicDropDown.test.tsx
  src/components/DynamicDropDown/DynamicDropDown.tsx
  src/components/UserPortal/UserSidebar/UserSidebar.test.tsx
  src/components/UserUpdate/UserUpdate.module.css
  src/components/UserUpdate/UserUpdate.test.tsx
  src/components/UserUpdate/UserUpdate.tsx
  src/screens/MemberDetail/MemberDetail.module.css
  src/screens/MemberDetail/MemberDetail.test.tsx
  src/screens/MemberDetail/MemberDetail.tsx
  src/utils/memberFields.ts
Labels: figma, Ready 4 PR Review

#1837 Eslint prettier conflict fix
  .eslintrc.json
  package-lock.json
  package.json
Labels: Ready 4 PR Review

#1834 Added tests for src/screens/OrganizationActionItems/ActionItemUpdateModal.tsx
  src/screens/OrganizationActionItems/ActionItemUpdateModal.test.tsx
  src/screens/OrganizationActionItems/ActionItemUpdateModal.tsx
Labels: Ready 4 PR Review
