Repository PalisadoesFoundation/talawa-admin, pull requests merged in 2024-12, with the labels that each got.

#2531 Update from develop-postgres 20241130
  .eslintignore
  .eslintrc.json
  .github/pull_request_template.md
  .github/workflows/codeql-codescan.yml
  .github/workflows/issue.yml
  .github/workflows/pull-request-target.yml
  .github/workflows/pull-request.yml
  .github/workflows/push.yml
  .github/workflows/stale.yml
  jest.config.js
  package-lock.json
  package.json
  src/assets/css/app.css
  src/components/AddOn/AddOn.spec.tsx
  src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.tsx
  src/components/CheckIn/tagTemplate.ts
  src/components/EventCalendar/EventCalendar.module.css
  src/components/EventCalendar/EventHeader.tsx
  src/components/LeftDrawer/LeftDrawer.test.tsx
  src/components/LeftDrawer/LeftDrawer.tsx
  src/components/LoginPortalToggle/LoginPortalToggle.module.css
  src/components/OrgListCard/OrgListCard.module.css
  src/components/Venues/VenueModal.tsx
  src/screens/BlockUser/BlockUser.tsx
  src/screens/LoginPage/LoginPage.module.css
  src/screens/LoginPage/LoginPage.tsx
  src/screens/OrgList/OrgList.module.css
  src/screens/OrgList/OrgList.tsx
  src/screens/OrgPost/OrgPost.tsx
  src/screens/OrganizationActionItems/OrganizationActionItems.tsx
  src/screens/OrganizationEvents/OrganizationEvents.module.css
  src/screens/OrganizationEvents/OrganizationEvents.tsx
  src/screens/OrganizationFunds/FundModal.tsx
  src/screens/OrganizationFunds/OrganizationFunds.tsx
  src/screens/OrganizationTags/OrganizationTags.tsx
  src/screens/OrganizationVenues/OrganizationVenues.tsx
  src/screens/Requests/Requests.module.css
  src/screens/Requests/Requests.tsx
  src/style/app.module.css
  tsconfig.json
  vitest.config.ts
Labels: ignore-sensitive-files-pr

#2501 Refactored src/components/AddOn/core/AddOnEntry/AddOnEntry.test.tsx from Jest to Vitest
  package-lock.json
  src/components/AddOn/core/AddOnEntry/AddOnEntry.spec.tsx
Labels: refactor

#2482 Refactored src/components/AddOn/support/components/Action/Action.test.tsx from Jest to Vitest
  src/components/AddOn/support/components/Action/Action.spec.tsx
  vitest.config.ts
  vitest.setup.ts
Labels: refactor

#2006 Plugin and advertisement screen revamp
  .github/pull_request_template.md
  public/locales/en/translation.json
  src/components/AddOn/core/AddOnEntry/AddOnEntry.module.css
  src/components/AddOn/core/AddOnEntry/AddOnEntry.tsx
  src/components/AddOn/core/AddOnStore/AddOnStore.module.css
  src/components/AddOn/core/AddOnStore/AddOnStore.test.tsx
  src/components/AddOn/core/AddOnStore/AddOnStore.tsx
  src/components/AddOn/support/services/Plugin.helper.test.ts
  src/components/Advertisements/Advertisements.module.css
  src/components/Advertisements/Advertisements.test.tsx
  src/components/Advertisements/Advertisements.tsx
  src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.module.css
  src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.tsx
  src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.module.css
Labels: ignore-sensitive-files-pr

#2804 Added Event Registrants Tab under Event Management Dashboard
  .eslintrc.json
  package-lock.json
  package.json
  public/images/svg/options-outline.svg
  public/images/svg/organization.svg
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/hi/translation.json
  public/locales/sp/translation.json
  public/locales/zh/translation.json
  src/GraphQl/Queries/Queries.ts
  src/components/CheckIn/CheckInWrapper.module.css
  src/components/CheckIn/CheckInWrapper.tsx
  src/components/CheckIn/tagTemplate.ts
  src/components/EventManagement/EventRegistrant/EventRegistrants.spec.tsx
  src/components/EventManagement/EventRegistrant/EventRegistrants.tsx
  src/components/EventManagement/EventRegistrant/Registrations.mocks.ts
  src/components/EventRegistrantsModal/EventRegistrantsWrapper.module.css
  src/components/EventRegistrantsModal/EventRegistrantsWrapper.test.tsx
  src/components/EventRegistrantsModal/EventRegistrantsWrapper.tsx
  src/screens/EventManagement/EventManagement.tsx
Labels: ignore-sensitive-files-pr

#2953 Configure & Install `docs-admin.talawa.io` Docusaurus Site
  .eslintignore
  .eslintrc.json
  .github/workflows/pull-request.yml
  .github/workflows/push.yml
  docs/.gitignore
  docs/CNAME
  docs/README.md
  docs/blog/2019-05-28-first-blog-post.md
  docs/blog/2019-05-29-long-blog-post.md
  docs/blog/2021-08-01-mdx-blog-post.mdx
  docs/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  docs/blog/2021-08-26-welcome/index.md
  docs/blog/authors.yml
  docs/blog/tags.yml
  docs/docs/intro.md
  docs/docs/tutorial-basics/_category_.json
  docs/docs/tutorial-basics/congratulations.md
  docs/docs/tutorial-basics/create-a-blog-post.md
  docs/docs/tutorial-basics/create-a-document.md
  docs/docs/tutorial-basics/create-a-page.md
  docs/docs/tutorial-basics/deploy-your-site.md
  docs/docs/tutorial-basics/markdown-features.mdx
  docs/docs/tutorial-extras/_category_.json
  docs/docs/tutorial-extras/img/docsVersionDropdown.png
  docs/docs/tutorial-extras/img/localeDropdown.png
  docs/docs/tutorial-extras/manage-docs-versions.md
  docs/docs/tutorial-extras/translate-your-site.md
  docs/docusaurus.config.ts
  docs/package.json
  docs/sidebars.ts
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  docs/src/pages/markdown-page.md
  docs/static/.nojekyll
  docs/static/CNAME
  docs/static/img/docusaurus-social-card.jpg
  docs/static/img/docusaurus.png
  docs/static/img/favicon.ico
  docs/static/img/logo.svg
  docs/static/img/markdown/misc/logo.png
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
Labels: ignore-sensitive-files-pr

#2954 Configure & Install docs-admin.talawa.io Docusaurus Site v2
  .nojekyll
Labels: ignore-sensitive-files-pr

#2956 Configure & Install docs-admin.talawa.io Docusaurus Site v3
  .github/workflows/push-deploy-website.yml
Labels: ignore-sensitive-files-pr

#2959 Configure & Install docs-admin.talawa.io Docusaurus Site v7
  .github/workflows/push-deploy-website.yml
Labels: ignore-sensitive-files-pr

#2960 Configure & Install docs-admin.talawa.io Docusaurus Site v9
  .github/workflows/push-deploy-website.yml
  .github/workflows/push.yml
Labels: ignore-sensitive-files-pr

#2962 v11 - Configure & Install docs-admin.talawa.io Docusaurus Site
  .github/workflows/push-deploy-website.yml
  .github/workflows/push.yml
Labels: ignore-sensitive-files-pr

#2964 v13 - Configure & Install docs-admin.talawa.io Docusaurus Site
  .github/workflows/push-deploy-website.yml
Labels: ignore-sensitive-files-pr

#2965 v14 - Configure & Install docs-admin.talawa.io Docusaurus Site
  .github/workflows/push-deploy-website.yml
Labels: ignore-sensitive-files-pr

#2966 v15 - Configure & Install docs-admin.talawa.io Docusaurus Site
  docs/docusaurus.config.ts
Labels: ignore-sensitive-files-pr

#2967 v16 - Configure & Install docs-admin.talawa.io Docusaurus Site
  .github/workflows/push-deploy-website.yml
Labels: ignore-sensitive-files-pr

#2969 v18 - Configure & Install docs-admin.talawa.io Docusaurus Site
  .github/workflows/push-deploy-website.yml
  .github/workflows/push.yml
Labels: ignore-sensitive-files-pr

#2606 Refactor: src/screens/BlockUser from Jest to Vitest
  package-lock.json
  package.json
  src/screens/BlockUser/BlockUser.spec.tsx
Labels: ignore-sensitive-files-pr

#2360 Added features to filter chats, edit messages, add users to group chat, share images as messages, and create dedicated group chats for events
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/hi/translation.json
  public/locales/sp/translation.json
  public/locales/zh/translation.json
  src/App.tsx
  src/GraphQl/Mutations/OrganizationMutations.ts
  src/GraphQl/Mutations/mutations.ts
  src/GraphQl/Queries/PlugInQueries.ts
  src/components/GroupChatDetails/GroupChatDetails.module.css
  src/components/GroupChatDetails/GroupChatDetails.test.tsx
  src/components/GroupChatDetails/GroupChatDetails.tsx
  src/components/UserPortal/ChatRoom/ChatRoom.module.css
  src/components/UserPortal/ChatRoom/ChatRoom.spec.tsx
  src/components/UserPortal/ChatRoom/ChatRoom.tsx
  src/components/UserPortal/ContactCard/ContactCard.module.css
  src/components/UserPortal/ContactCard/ContactCard.spec.tsx
  src/components/UserPortal/ContactCard/ContactCard.tsx
  src/components/UserPortal/CreateDirectChat/CreateDirectChat.spec.tsx
  src/components/UserPortal/CreateDirectChat/CreateDirectChat.tsx
  src/components/UserPortal/CreateGroupChat/CreateGroupChat.module.css
  src/components/UserPortal/CreateGroupChat/CreateGroupChat.spec.tsx
  src/components/UserPortal/CreateGroupChat/CreateGroupChat.tsx
  src/components/UserPortal/UserSidebar/UserSidebar.spec.tsx
  src/components/UserPortal/UserSidebar/UserSidebar.tsx
  src/screens/OrganizationEvents/OrganizationEvents.tsx
  src/screens/UserPortal/Chat/Chat.module.css
  src/screens/UserPortal/Chat/Chat.spec.tsx
  src/screens/UserPortal/Chat/Chat.tsx
  src/screens/UserPortal/Events/Events.spec.tsx
  src/screens/UserPortal/Events/Events.tsx
  src/state/reducers/userRoutersReducer.spec.ts
  src/state/reducers/userRoutesReducer.ts
Labels: wip, GSoC Priority

#3008 Added Code Rabbit Approval Check to pull-request.yml Workflow
  .github/workflows/pull-request.yml
  .github/workflows/scripts/validate-coderabbit.sh
Labels: ignore-sensitive-files-pr

#3100 Feature/admin docs refactor/admin-doc to hashura docs style
  docs/docusaurus.config.ts
  docs/src/css/custom.css
  docs/src/pages/index.tsx
  docs/static/img/icons/facebook.svg
  docs/static/img/icons/favicon_palisadoes.ico
  docs/static/img/icons/github-dark.svg
  docs/static/img/icons/github.svg
  docs/static/img/icons/instagram.svg
  docs/static/img/icons/opportunities.svg
  docs/static/img/icons/slack.svg
  docs/static/img/icons/source.svg
  docs/static/img/icons/team.svg
  docs/static/img/icons/twitter.svg
  docs/static/img/icons/youtube-white.svg
  docs/static/img/icons/youtube.svg
Labels: ignore-sensitive-files-pr
